# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f30e0fd07afbf88ca465bb3460e1236cff7d4119b5f6af09e5821bc690b8496bd1f60af94fcbab7f305036d341f3a71ac1e7075e7be0d9b9db0f346bb9116cd8

test:
  secret_key_base: e6ca13a20cf48671aa2693862ad5758dcd6250e5dcd701086cc3d7cf36bdb8c4d63c4120ff91e6f44db9e7242cb94db77b711f5cbdb6fe286099eb552541b32c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
